### PR TITLE
Some QoL improvements

### PR DESCRIPTION
**Pull request by oli-obk**
I played a bit around with a friend (them in VR, me on the flycam on the computer at the same time). Some things we noticed and I fixed in this PR

* VR player speed is waaay too low
* flycam speed is too low
* VR player cannot see where the flycam player is
* The sun (and thus shadows) were moving very fast

### CODE REVIEW

**Comment by DerKarlos** [comment]
This main.rs was just a Bevy example, and a default control, I found in the crates, partly modified for OSM.
Consider me as a enfant, playing with Bricks, I don't realy know.

* VR player / flycam / The sun:
We should have a control mimicking f4map.com. I started. See old deleted files. They may come back, if you give me time.
* VR player cannot see where the flycam player is:
What? Isn't both the same? FlyCam is the camera, controlled by the NoCameraPlayerPlugin?

**Comment by oli-obk** [comment]
> * What? Isn't both the same? FlyCam is the camera, controlled by the NoCameraPlayerPlugin?

Nope, two different controllers. I like this a lot, because then one person can walk around with mouse and keyboard while the other walks around in VR (when the headset is connected via cable, there's no network involved. It's one program doing both at the same time, similar to splitscreen games)

**Comment by DerKarlos** [comment]
Approve: Submit feedback and approve merging the changes proposed in the pull request.
Nice, but how to approve?

**Comment by DerKarlos** [comment]
GitHub and me are not friends yet.
How to Approve?

**Comment by oli-obk** [comment]
First 
Screenshot_Fennec_20231120-184646~3

Then

Screenshot_Fennec_20231120-184651~2

Or did you mean approve but not merge? You can do that in the "files changed" view

Screenshot_Fennec_20231120-185643~2

**Review by DerKarlos — APPROVED** [review]

**Pull request merged**
